<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-04-23 15:07
=======
# Generated by Django 4.1.2 on 2023-04-23 14:38
>>>>>>> b4926aa2b9c19266b77d6c66bbd20885e145c27d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=30)),
                ('oops', models.IntegerField()),
                ('dbms', models.IntegerField()),
                ('cn', models.IntegerField()),
                ('os', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
