# Generated by Django 4.1.2 on 2023-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalquestions_api', '0002_alter_results_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=5000)),
                ('question', models.TextField(max_length=5000)),
                ('option_a', models.CharField(max_length=5000)),
                ('option_b', models.CharField(max_length=5000)),
                ('option_c', models.CharField(max_length=5000)),
                ('option_d', models.CharField(max_length=5000)),
                ('correct_answer', models.CharField(max_length=5000)),
                ('difficulty', models.CharField(max_length=5000)),
                ('cognitive_level', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=5000)),
            ],
        ),
    ]
